fx_version 'cerulean'
games { 'gta5' }
this_is_a_map 'yes'
files {
	'common/*.meta'
}
data_file 'DLC_ITYP_REQUEST' 'stream/country_01_metadata_015.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_01_metadata_015_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_001.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_001_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_002.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_002_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_003.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_003_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_004.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_004_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_005.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_005_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_006.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_006_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_007.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_007_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_008.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_008_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_009.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_009_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_010.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_010_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_011.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_011_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_012.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_012_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_04_metadata_013.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_001.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_001_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_002.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_002_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_003.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_003_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_004.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_004_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_005.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_005_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_006.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_006_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_007.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_007_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_008.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_008_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_009.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_009_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_010.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_010_strm.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_011.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_012.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/country_06_metadata_013.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/cs4_lod.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/cs4_railwayb_interior_cs4_rwayb_tunnelint.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/cs6_08_interior_cs6_08_mine_int.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/cs6_lod.ytyp'
data_file 'DLC_ITYP_REQUEST' 'stream/int4.ytyp'
